# Generated by Django 3.0.8 on 2020-07-08 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('last_edit', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('project_description', models.TextField(default='No Description.')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('last_edit', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('task_notes', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_works.Project')),
            ],
        ),
    ]
