# Generated by Django 3.0.8 on 2020-07-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_works', '0002_auto_20200708_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='notes',
            new_name='description',
        ),
    ]
