# Generated by Django 3.0.8 on 2020-07-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_works', '0003_auto_20200710_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='No Description.'),
        ),
    ]
